[package]
name = "Ur"
version = "0.1.0"
authors = ["alban <alban.reynaud@laposte.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "main"
path = "src/main.rs"
